setup;

dbTrain= dbTokyoTimeMachine('train');
dbVal= dbTokyoTimeMachine('val');

sessionID= trainWeakly(dbTrain, dbVal, ...
    'netID', 'vd16', 'layerName', 'conv5_3', 'backPropToLayer', 'conv5_1', ...
    'method', 'vlad_preL2_intra', ...
    'learningRate', 0.0001, ...
    'doDraw', true, ...
    'useGPU', false);
[~, bestNet]= pickBestNet(sessionID);


